server {

    location = / {
        return 302 /pages/login/;
    }


    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /pages/login/index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_pass http://mbio-signalbot:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
